### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by noxone** [noxone/mahjong-point-calculator#7]
- [x] #8
- [x] Improve Mahjong-checkboxes... separate them from the other options
- [x] Better design for result button
- [x] improve placement of tiles
- [x] #14
- [x] better styling for prevailing and seat wind
- [x] #12
- [x] Improve display on small screens
- [x] Improve display on slightly smaller displays like iPad Mini
- [x] Maybe make tile insertion more intelligent. When a user clicks on a tile that does not fit, add it to the next figure - yes/ no?
- [x] Create `undo` functionality
- [x] Show "hidden" figures by "hiding" a tile
- [x] Improve display of tiles if there are too many in one figure (stack them over each other)
- [x] Only activate "Reset" for a figure if there are tiles in
- [x] Add clarity integration
- [x] #9
- [x] #11
- [x] #15
- [x] Somehow make it more obvious, that a player has "Mahjong"
- [x] Improve font size of "open"/ "closed" text for smaller screens
- [x] Mark a tile red if clicked and it is not available
- [x] #26
- [x] Only activate Mahjong checkboxes if player has mahjong

Things that probably wont be done:
- _Show the "Reset" Popover also on hover when not running on a touch device._ Because the browser cannot detect, whether or not the current device is a touch device or not.
